#ifndef ProtocolH
#define ProtocolH

// Packet ID components, from eo-protocol xml/net/protocol.xml. Every outgoing
// packet is identified by a (family, action) pair; the reconstructed helpers
// (Client_SendEncoded, Server_BroadcastToMap, Server_BroadcastNearby) take them
// as (action, family), matching the reference call sites.
enum PacketFamily
{
    PacketFamily_Connection = 1,
    PacketFamily_Account = 2,
    PacketFamily_Character = 3,
    PacketFamily_Login = 4,
    PacketFamily_Welcome = 5,
    PacketFamily_Walk = 6,
    PacketFamily_Face = 7,
    PacketFamily_Chair = 8,
    PacketFamily_Emote = 9,
    PacketFamily_Attack = 11,
    PacketFamily_Spell = 12,
    PacketFamily_Shop = 13,
    PacketFamily_Item = 14,
    PacketFamily_StatSkill = 16,
    PacketFamily_Global = 17,
    PacketFamily_Talk = 18,
    PacketFamily_Warp = 19,
    PacketFamily_Jukebox = 21,
    PacketFamily_Players = 22,
    PacketFamily_Avatar = 23,
    PacketFamily_Party = 24,
    PacketFamily_Refresh = 25,
    PacketFamily_Npc = 26,
    PacketFamily_PlayerRange = 27,
    PacketFamily_NpcRange = 28,
    PacketFamily_Range = 29,
    PacketFamily_Paperdoll = 30,
    PacketFamily_Effect = 31,
    PacketFamily_Trade = 32,
    PacketFamily_Chest = 33,
    PacketFamily_Door = 34,
    PacketFamily_Message = 35,
    PacketFamily_Bank = 36,
    PacketFamily_Locker = 37,
    PacketFamily_Barber = 38,
    PacketFamily_Guild = 39,
    PacketFamily_Music = 40,
    PacketFamily_Sit = 41,
    PacketFamily_Recover = 42,
    PacketFamily_Board = 43,
    PacketFamily_Cast = 44,
    PacketFamily_Arena = 45,
    PacketFamily_Priest = 46,
    PacketFamily_Marriage = 47,
    PacketFamily_AdminInteract = 48,
    PacketFamily_Citizen = 49,
    PacketFamily_Quest = 50,
    PacketFamily_Book = 51,
    PacketFamily_Error = 250,
    PacketFamily_Init = 255
};

enum PacketAction
{
    PacketAction_Request = 1,
    PacketAction_Accept = 2,
    PacketAction_Reply = 3,
    PacketAction_Remove = 4,
    PacketAction_Agree = 5,
    PacketAction_Create = 6,
    PacketAction_Add = 7,
    PacketAction_Player = 8,
    PacketAction_Take = 9,
    PacketAction_Use = 10,
    PacketAction_Buy = 11,
    PacketAction_Sell = 12,
    PacketAction_Open = 13,
    PacketAction_Close = 14,
    PacketAction_Msg = 15,
    PacketAction_Spec = 16,
    PacketAction_Admin = 17,
    PacketAction_List = 18,
    PacketAction_Tell = 20,
    PacketAction_Report = 21,
    PacketAction_Announce = 22,
    PacketAction_Server = 23,
    PacketAction_Drop = 24,
    PacketAction_Junk = 25,
    PacketAction_Obtain = 26,
    PacketAction_Get = 27,
    PacketAction_Kick = 28,
    PacketAction_Rank = 29,
    PacketAction_TargetSelf = 30,
    PacketAction_TargetOther = 31,
    PacketAction_TargetGroup = 33,
    PacketAction_Dialog = 34,
    PacketAction_Ping = 240,
    PacketAction_Pong = 241,
    PacketAction_Net242 = 242,
    PacketAction_Net243 = 243,
    PacketAction_Net244 = 244,
    PacketAction_Error = 250,
    PacketAction_Init = 255
};

#endif
